# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TasksApp_Final_Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TasksApp_Final_Project
  	pod 'Firebase/Core' 
  	pod 'FirebaseUI/Auth'
    pod 'GoogleSignIn'
    pod 'Firebase/Database'
	pod "ForecastIO"


  target 'TasksApp_Final_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TasksApp_Final_ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
